# Cloud PostgreSQL Database (Neon.tech)
spring.datasource.url=jdbc:postgresql://ep-soft-smoke-b3gjexi6.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_n1Yjd2SsvzUg
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080